#!/usr/bin/env python3
import r2d2.repo
from r2d2.color import *

repo = None
try:
    repo = r2d2.repo.Repo(git_folder='.git')
except ValueError as e:
    exit(e)

merge_request = repo.current_branch.merge_requests()[0]

print("On branch " + whiteb(repo.current_branch.name))

print(f"MR URL: {bright(merge_request.web_url)}")

# State
if merge_request.state == "merged":
    print(green(f"State: {merge_request.state}"))
elif merge_request.state == "opened":
    print(magenta(f"State: {merge_request.state}"))
else:
    print(red(f"State: {merge_request.state}"))

# approvals
approvals = merge_request.approvals()
approvals_left = approvals.approvals_left
if approvals_left == 0:
    print(green(f"Approvals left: {approvals.approvals_left}"))
else:
    print(red(f"Approvals left: {approvals.approvals_left}"))

# Pipeline
pipelines = merge_request.pipelines()
pipeline_status = pipelines[0].status
if pipeline_status == "success":
    print(green(f"pipeline: {pipeline_status}"))
else:
    print(red(f"pipeline: {pipeline_status}"))

print(f"Description: {merge_request.data['description']}")
