#!/usr/bin/env python3

from gitr2d2.repo import Repo
from gitr2d2.color import greenb, green, magenta, white, whiteb

MASTER = 'master'
DEV = 'development15'

repo = Repo()

branches = repo.local_branches()
current = repo.current_branch()
name_width = max([len(branch.name) for branch in branches])

for branch in branches:
    # * branch_name
    line = ''
    if branch.name == current.name:
        line += whiteb('* ')
        if branch.is_merged(MASTER):
            line += greenb(f"{branch.name:{name_width}}")
        else:
            line += whiteb(f"{branch.name:{name_width}}")
    else:
        line += '  '
        if branch.is_merged(MASTER):
            line += green(f"{branch.name:{name_width}}")
        else:
            line += white(f"{branch.name:{name_width}}")

    # is merged to development
    if branch.is_merged(DEV):
        line += magenta(' DEV')
    else:
        line += ' ---'

    # MR weblink
    if mrs := branch.merge_requests():
        mr = mrs[0]
        line += ' ' + mr.web_url

    # description
    line += ' ' + branch.description()

    print(line)

