#!/usr/bin/env python3
from githelpers import run
from colorama import init, Fore, Style

init(autoreset=True)

current = run('git rev-parse --abbrev-ref HEAD')
branches = run("git for-each-ref --format='%(refname)' refs/heads/ | sed 's|refs/heads/||'").split('\n')
for branch in branches:
    description = run(f"git config branch.{branch}.description")
    if branch == current:
        branch = f"{Fore.YELLOW}{Style.BRIGHT}{branch}{Style.NORMAL}"
    desc, *mr = description.split('|', 2)
    desc = f"{Fore.CYAN}{desc.strip()}"
    mr = Fore.BLUE + " ".join(mr).strip() if mr else ''
    print(branch, desc, mr)



