#!/usr/bin/env python3

import r2d2.repo
from r2d2.color import *


MASTER = 'master'
DEV = 'development15'

repo = None
try:
    repo = r2d2.repo.Repo(git_folder='.git')
except ValueError as e:
    exit(e)

branches = repo.local_branches()
name_width = max([len(branch.name) for branch in branches])

for branch in branches:
    # * branch_name
    line = ''
    if branch.name == repo.current_branch.name:
        line += whiteb('* ')
        if branch.is_merged_in(MASTER):
            line += greenb(f"{branch.name:{name_width}}")
        else:
            line += whiteb(f"{branch.name:{name_width}}")
    else:
        line += '  '
        if branch.is_merged_in(MASTER):
            line += green(f"{branch.name:{name_width}}")
        else:
            line += white(f"{branch.name:{name_width}}")

    # is merged to development
    if branch.is_merged_in(DEV):
        line += magenta(' DEV')
    else:
        line += ' ---'

    # MR weblink
    if mrs := branch.merge_requests():
        mr = mrs[0]
        line += ' ' + mr.web_url

    # description
    line += ' ' + branch.description()

    print(line)
